# -*- coding: utf-8 -*-
"""Clorophyll plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luERkeVFkRvkRgI48nebMn7BvKNyJJEL
"""

import json
import os

import cv2
import matplotlib

import helpers as hlp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import cm

# # you can ommit this part, this is to go to the working folder
# from google.colab import drive
# drive.mount('/content/drive', force_remount= True)
# path = 'drive/MyDrive/FIU/Research/Experiments/Plotting the clorophyll'
# os.chdir(path)
# !ls
# Load data and mask
# data[i][j][k] = [predicted_do, predicted_chla, predicted_temp, predicted_turb]
sdue = np.load('../data/level_4/20221007_SDUE.npy')

# Split data into 4 separate 3D arrays
predicted_do = sdue[:, :, :, 0]
predicted_chla = sdue[:, :, :, 1]
predicted_temp = sdue[:, :, :, 2]
predicted_turb = sdue[:, :, :, 3]

predictions = [
predicted_do,
predicted_chla,
predicted_temp,
predicted_turb
]

titles = [
'3-D Satellite Derived Dissolved Oxygen',
'3-D Satellite Derived Chlorophyll-a',
'3-D Satellite Derived Temperature',
'3-D Satellite Derived Turbidity'
]

units = [
'ODO (mg/L)',
'Chlorophyll-a (ug/l)',
'Temperature (°C)',
'Turbidity FNU'
]

file_names = [
'do',
'chla',
'temp',
'turb'
]

color_maps = [
cm.winter_r,
cm.summer_r,
cm.autumn_r,
cm.copper_r
]

for i in range(len(predictions)):
    data = predictions[i]
    hlp.plot_sdue_contourf(data, titles[i], units[i],  high_concentration_color_or_cmap = color_maps[i],file_prefix = file_names[i], show_tick_labels = False)
